import esbuild from 'esbuild';
import less from 'less';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'process';
import { builtinModules } from 'node:module';
import { watch } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const cssBanner = `/*
THIS IS A GENERATED/BUNDLED FILE FROM style.less
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const root = process.cwd();
const styleEntry = resolve(root, 'style.less');
const styleOut = resolve(root, 'styles.css');

async function buildStyles() {
	const input = await readFile(styleEntry, 'utf8');
	const result = await less.render(input, {
		filename: styleEntry,
		paths: [root],
	});
	await mkdir(dirname(styleOut), { recursive: true });
	await writeFile(styleOut, `${cssBanner}\n${result.css}`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

await buildStyles();

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();

	const styleDir = resolve(root, 'style');
	const rebuildStyles = async () => {
		try {
			await buildStyles();
			console.log('[less] styles.css rebuilt');
		} catch (error) {
			console.error('[less] build failed', error);
		}
	};

	watch(styleEntry, rebuildStyles);
	watch(styleDir, { recursive: true }, rebuildStyles);
}
